### ISSUE TITLE
Using Element::get<Color> has surprising defaults

### ISSUE THREAD

**Issue by osrf-migration** [osrf/sdformat#193]
**Original report ([archived issue](https://osrf-migration.github.io/sdformat-gh-pages/#!/osrf/sdformat/issues/193)) by SeanCurtis-TRI (Bitbucket: [SeanCurtis-TRI](https://bitbucket.org/%7Bfc23d5a9-ee84-4708-929f-c7bce7adc656%7D/)).**

----------------------------------------
When parsing a `<material>`  tag for (e.g.,) diffuse color information, one can do the following (assuming that `material_element` is an `sdf::Element`):

```c++
Color default_color(0.25, 0.5, 0.75, 0.8);
material_element.Get<Color>("diffuse", default_color);
```

The specification suggests that the corresponding tag should look like:
`<diffuse>r g b a</diffuse>`

However, the following tags produce the following colors:
`<diffuse>1</diffuse` --> 1 0 0 1
`<diffuse>1 0.25</diffuse>` --> 1 0.25 0 1
`<diffuse>1 0.25 0.5</diffuse>` --> 1 0.25 0.5 1
`<diffuse>1 0.25 0.5 0.75 2</diffuse>` --> 1 0.25 0.5 0.75

The rules I infer are:

1.   If a is missing, use the default value 1.
2.  if r, g, or b are missing, use the default value 0
3.  If there are two many values, simply truncate.

I think this is *incredibly* counter-intuitive and not strictly helpful. One can make solid arguments that supplying rgb (in place of rgba) is a reasonable overload. But all of the rest seem kind of insane.

**Comment by EricCousineau-TRI** [comment]
Still awkward in https://github.com/robotlocomotion/drake/pull/14705
\cc @seancurtis-tri
