### ISSUE TITLE
Please respect the BUILD_TESTING variable

### ISSUE THREAD

**Issue by osrf-migration** [osrf/sdformat#208]
**Original report ([archived issue](https://osrf-migration.github.io/sdformat-gh-pages/#!/osrf/sdformat/issues/208)) by yurivict (Bitbucket: [yurivict](https://bitbucket.org/%7B7012cf74-23b1-4689-8f6d-63be51ab0d44%7D/)).**

----------------------------------------
There is no need to build tests by default, only with ```BUILD_TESTING=ON```.

https://cmake.org/cmake/help/v3.0/module/CTest.html

**Comment by azeey** [comment]
This has been fixed by https://github.com/osrf/sdformat/pull/269. However, the behavior is to build tests unless `BUILD_TESTING=OFF`.
