### ISSUE TITLE
urdfdom and urdfdom_header not found when building from source on OSX

### ISSUE THREAD

**Issue by osrf-migration** [osrf/sdformat#224]
**Original report ([archived issue](https://osrf-migration.github.io/sdformat-gh-pages/#!/osrf/sdformat/issues/224)) by Claire Wang (Bitbucket: [Claire Wang](https://bitbucket.org/%7B4b4ab2f2-8148-463e-a671-2eed1e6ccd42%7D/), GitHub: [claireyywang](https://github.com/claireyywang)).**

----------------------------------------
# Prerequisites

* \[X\] Put an X between the brackets on this line if you have done all of the following:

    * Checked the Q&A board for common solutions: [http://answers.gazebosim.org](http://answers.gazebosim.org)
    * Checked that your issue isn't already filed.
    * Checked that there is not already an Ignition package that provides the described functionality: [https://ignitionrobotics.org/libs](https://ignitionrobotics.org/libs)
    

# Description

\[Description of the issue\]  
After installing urdfdom package with brew, cmake is still unable to find it during the build process.

# Steps to Reproduce

1. \[First Step\] brew install urdfdom
2. \[Second Step\] colcon build --merge-install
3. \[and so on...\]

**Expected behavior:**

\[What you expect to happen\]  
Builds sdformat9 successfully

**Actual behavior:**

\[What actually happens\]

```
/Users/clairewang/citadel_ws/src/sdformat/src/parser_urdf.cc:30:10: fatal error: 'urdf_model/model.h' file not found

#include <urdf_model/model.h>^~~~~~~~1 error generated.make[2]: *** [src/CMakeFiles/sdformat9.dir/parser_urdf.cc.o] Error 1make[1]: *** [src/CMakeFiles/sdformat9.dir/all] Error 2make: *** [all] Error 2make: INTERNAL: Exiting with 14 jobserver tokens available; should be 12!

Failed <<< sdformat9 [ Exited with code 2 ]
```

**Reproduces how often:**

\[What percentage of the time does it occur?\]  
All the time when I build from source

# Versions

\[Include information about relevant software versions, and your OS type and version.\]

OS: Mojave \(10.14\)  
Ignition: Citadel  
Xcode: 10.3

# Additional Information

\[Any additional information, configuration or data that might be necessary to reproduce the issue.\]

The current workaround is to use `colcon build --cmake-args -DUSE_INTERNAL_URDF=ON --merge-install`, but it would be nice to build with the system one.

‌

**Comment by scpeters** [comment]
this was fixed by the following pull requests:

* [BitBucket pull request 677](https://osrf-migration.github.io/sdformat-gh-pages/#!/osrf/sdformat/pull-requests/677)
* [BitBucket pull request 686](https://osrf-migration.github.io/sdformat-gh-pages/#!/osrf/sdformat/pull-requests/686)
