### ISSUE TITLE
Associate sdf::Element with line number in file

### ISSUE THREAD

**Issue by osrf-migration** [osrf/sdformat#226]
**Original report ([archived issue](https://osrf-migration.github.io/sdformat-gh-pages/#!/osrf/sdformat/issues/226)) by Anonymous.**

----------------------------------------
Currently, during parsing, it is impossible to examine an arbitrary sdf::Thing (or sdf::Element) and provide any feedback on the element and link it to where it came from in the original source file. This definitely handicaps error and warning messages.

**Comment by EricCousineau-TRI** [comment]
As an interim (pre-`tinyxml2`), it may possible to still provide more information by means of tracing with an XPath error.

I had tinkered with something like this in `urdf_parser_py`, inspired by some MathWorks-related code. Example:
https://github.com/ros/urdf_parser_py/blob/f7f25be76c5dfbe51d4e87367553ec180d8f5683/test/test_urdf_error.py#L124

**Comment by EricCousineau-TRI** [comment]
FYI @aaronchongth
