### ISSUE TITLE
Should update CI to work for GitHub sdformat

### ISSUE THREAD

**Issue by EricCousineau-TRI** [osrf/sdformat#242]
UPDATE: For CI in general.

- [x] Jenkins
- [ ] CodeCov

---

OLD: Specific to CodeCov
Currently, it looks like the codecov.io badge still uses BitBucket, and links here:
https://codecov.io/bb/osrf/sdformat

At current commit:
https://github.com/osrf/sdformat/blob/96cc8d2fdfac192422268dd16d05b4c861e778e1/README.md

**Comment by EricCousineau-TRI** [comment]
Per VC with @scpeters, this will be handled in a larger effort for CI on BitBucket -> GitHub migration.

**Comment by scpeters** [comment]
this will be fixed by #255

**Comment by scpeters** [comment]
this was finished by #255
