### ISSUE TITLE
Supporting parsing "inf", "+inf", "-inf"

### ISSUE THREAD

**Issue by azeey** [osrf/sdformat#261]
To best enable: #249

**Comment by scpeters** [comment]
I've added tests in #277 that confirm that `+Inf` and `-Inf` can already be parsed successfully.

**Comment by scpeters** [comment]
I've just discovered that this doesn't work for elements that aren't part of the schema, such as elements within a `<plugin/>` block. The `typeName` for Element values that aren't part of the schema [defaults to `"string"`](https://github.com/osrf/sdformat/blob/sdformat11_11.1.0/src/parser.cc#L1489), and I've repeated the tests from #277 for elements with `"string"` `typeName` in https://github.com/osrf/sdformat/commit/9c7f328639e96b0d39e7a703f67d72096a29e774 (branch [scpeters:get_inf_from_string](https://github.com/osrf/sdformat/compare/sdf9...scpeters:get_inf_from_string?expand=1), and they fail.

**Comment by scpeters** [comment]
I can create a separate ticket if you think I should leave this closed.

**Comment by scpeters** [comment]
> I've just discovered that this doesn't work for elements that aren't part of the schema, such as elements within a `<plugin/>` block. The `typeName` for Element values that aren't part of the schema [defaults to `"string"`](https://github.com/osrf/sdformat/blob/sdformat11_11.1.0/src/parser.cc#L1489), and I've repeated the tests from #277 for elements with `"string"` `typeName` in [9c7f328](https://github.com/osrf/sdformat/commit/9c7f328639e96b0d39e7a703f67d72096a29e774) (branch [scpeters:get_inf_from_string](https://github.com/osrf/sdformat/compare/sdf9...scpeters:get_inf_from_string?expand=1), and they fail.

we discovered this during review of https://github.com/ignitionrobotics/ign-gazebo/pull/833#issuecomment-857069329

**Comment by azeey** [comment]
@scpeters yes, I think a separate ticket would be better. I'll go ahead and create one.

**Comment by azeey** [comment]
https://github.com/osrf/sdformat/issues/603
