### ISSUE TITLE
Make included models work as nested models via DOM in libsdformat10

### ISSUE THREAD

**Issue by EricCousineau-TRI** [osrf/sdformat#284]
Requires #283
Towards https://github.com/osrf/sdformat/issues/278

**Comment by scpeters** [comment]
I've experimented with this in https://github.com/scpeters/sdformat/commit/52fe7026e66d5ca5def977304541d6cbf38751d7 by replacing the call to `addNestedModel` by directly inserting the model element, but it needs the global graph to work properly (https://github.com/osrf/sdformat/issues/293)

**Comment by EricCousineau-TRI** [comment]
Resolved by #381
