### ISSUE TITLE
Permit detecting an element / attribute was explicitly set (user) or implicitly set (conversion / default value)

### ISSUE THREAD

**Issue by EricCousineau-TRI** [osrf/sdformat#287]
From discussion on 2020-01-23 on Asana.

Notes:
Default values
* Know if a property was actually defined
* `libsdformat`, in its conversion phase, substitutes in default values
* Odd / non-strict value parsing (e.g. colors, RGBA)
* API: Could add an attribute check, `IsExplicitlySet()` or `UsedDefaultValue()` or something, and have overloads for querying that uses `optional<>` or returns a flag
* May be hard to check if a default value was actually set?
* Could be useful for deprecating attributes that a user set?

\cc @SeanCurtis-TRI

**Comment by EricCousineau-TRI** [comment]
\cc @marcoag

**Comment by azeey** [comment]
Waiting for https://github.com/osrf/sdformat/pull/575#issuecomment-845191669 to be resolved before closing.

**Comment by marcoag** [comment]
Resolved: https://github.com/osrf/sdformat/pull/575#issuecomment-869458363. Closing this issue then.
