### ISSUE TITLE
//joint/axis/xyz: Should normalize, or fail if norm(xyz) < tol

### ISSUE THREAD

**Issue by EricCousineau-TRI** [osrf/sdformat#307]
At present, `JointAxis` asks for vectors to be normalized, but does not enforce / fix it:
https://github.com/osrf/sdformat/blob/55029bbf533b26ddb2ea35acfdb4e1c7434a401e/include/sdf/JointAxis.hh#L85-L87

Ideal:
* If `norm(xyz) < eps`, fail. Normalizing this is junk.
* Otherwise, `xyz /= norm(xyz)`.

**Comment by azeey** [comment]
Resolved by #312
