### ISSUE TITLE
Unable to find tinyxml2 in focal builds

### ISSUE THREAD

**Issue by scpeters** [osrf/sdformat#320]
Our nightly builds of `libsdformat10` are failing on focal due to problems finding tinyxml2:

* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=sdformat10-debbuilder&build=9)](https://build.osrfoundation.org/job/sdformat10-debbuilder/9/) https://build.osrfoundation.org/job/sdformat10-debbuilder/9/console

~~~
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find TinyXML2 (missing: TINYXML2_LIBRARY TINYXML2_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindTinyXML2.cmake:31 (find_package_handle_standard_args)
  cmake/SearchForStuff.cmake:11 (find_package)
  CMakeLists.txt:114 (include)


-- Configuring incomplete, errors occurred!
~~~

cc @mjcarroll

**Comment by mjcarroll** [comment]
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=sdformat10-debbuilder&build=28)](https://build.osrfoundation.org/job/sdformat10-debbuilder/28/) https://build.osrfoundation.org/job/sdformat10-debbuilder/28/console
