### ISSUE TITLE
Should support nested canonical links for libsdformat (implicit for 9/10, implicit+explicit for 11)

### ISSUE THREAD

**Issue by EricCousineau-TRI** [osrf/sdformat#342]

**Comment by scpeters** [comment]
With the implementation merged in #341, I think the update to the proposal in https://github.com/osrf/sdf_tutorials/pull/40 will complete this task

**Comment by EricCousineau-TRI** [comment]
PR: #355

**Comment by EricCousineau-TRI** [comment]
To clarify, explicit nesting will come as part of #293. This issue will be closed before then, but the proposal will help track this feature.

**Comment by scpeters** [comment]
I think this has been finished
