### ISSUE TITLE
Ampersands not showing in generated SDF collide bitmask doc 

### ISSUE THREAD

**Issue by PeterMitrano** [osrf/sdformat#375]
The documentation source says
```Collision happens if ((category1 & collision2) | (category2 & collision1)) is not zero.```

Unfortunately the ampersands get lost in generating the html, and the website shows this, which is quite confusing

![2020-09-18-003449_347x82_scrot](https://user-images.githubusercontent.com/4010770/93556477-cf598980-f946-11ea-843e-481707e2b578.png)

**Comment by EricCousineau-TRI** [comment]
@claireyywang Might you have time to look into this by Jan. 21?

**Comment by claireyywang** [comment]
@EricCousineau-TRI yeah sure I'll take a look.

**Comment by PeterMitrano** [comment]
Nice to see TRI investing in these open source projects! Thanks from UMich :)

**Comment by EricCousineau-TRI** [comment]
Should run `xmllint` on the corresponding schema `*.sdf` files. If the `&` exists directly in the files, they should use the `&amp;` escape character.

**Comment by azeey** [comment]
Fixed by #483
