### ISSUE TITLE
Should support capsule and ellipsoid for SDFormat 1.8 (libsdformat11)

### ISSUE THREAD

**Issue by EricCousineau-TRI** [osrf/sdformat#376]
Per f2f

**Comment by scpeters** [comment]
draft PR for capsule in #389

**Comment by brawner** [comment]
Similar PR for ellipsoid added in https://github.com/osrf/sdformat/pull/434
ignition-math PR: https://github.com/ignitionrobotics/ign-math/pull/182

**Comment by chapulina** [comment]
Both geometry types have been merged, can this be closed?
