### ISSUE TITLE
sdformat.com doesn't have documentation of sdf elements and versions

### ISSUE THREAD

**Issue by osrf-migration** [osrf/sdformat#4]
**Original report ([archived issue](https://osrf-migration.github.io/sdformat-gh-pages/#!/osrf/sdformat/issues/4)) by Steve Peters (Bitbucket: [Steven Peters](https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/), GitHub: [scpeters](https://github.com/scpeters)).**

----------------------------------------
I'm thinking of this: http://gazebosim.org/sdf/dev.html

**Comment by scpeters** [comment]
http://sdformat.org/spec
