### ISSUE TITLE
Should store an included model's source file name

### ISSUE THREAD

**Issue by azeey** [osrf/sdformat#401]
This can be useful when a world is saved. Relates to a TODO in https://github.com/osrf/sdformat/blob/144f82cf8b994abd2a566a7bbe6ae873a9d92403/src/parser.cc#L1075-L1082

**Comment by EricCousineau-TRI** [comment]
Can you illustrate this workflow, or point to a Gazebo tutorial / unittest that illustrates the nested model filenames being kept?

**Comment by azeey** [comment]
I don't think there is currently an example of this, but when saving worlds in ign-gazebo, there is an option to preserve the `<include>` tag as opposed to expanding it to a `<model>`. This worked by making use of `sdf::Element::FilePath` of the included model (https://github.com/ignitionrobotics/ign-gazebo/blob/5348afa4b5ae4349f72aca51af01db856ae65b90/src/SdfGenerator.cc#L101-L124). This was somewhat of a workaround for the lack of information regarding what file the model was loaded from. It is also unable to retrieve any other information included in the original `<include>` element, such as `<plugin>` or any custom elements.

#509 addresses this by storing the original content of the `<include>` element so it can be retrieved at a later time for such purposes.

**Comment by EricCousineau-TRI** [comment]
Sweet! Thanks!
