### ISSUE TITLE
Using the delimiter "::" in a name should be an error in SDFormat 1.8

### ISSUE THREAD

**Issue by azeey** [osrf/sdformat#420]
Per the SDFormat 1.8 composition [proposal](http://sdformat.org/tutorials?tut=composition_proposal&cat=pose_semantics_docs&#1-3-1-reserved-delimiter-token), the `::` delimiter is reserved for forming scopes, thus, it should not be used in `name` attributes. However, SDFormat 1.7 files can contain `::` in `name` attributes as a result of model flattening. So, we should only emit an error if the file is SDFormat 1.8.

**Comment by EricCousineau-TRI** [comment]
Requires https://github.com/osrf/sdformat/issues/411 before we can make this change.
