### ISSUE TITLE
Add Ignition Utils as dependency from libSDFormat 11

### ISSUE THREAD

**Issue by chapulina** [osrf/sdformat#467]
The new Ignition package has minimal dependencies and provides utility functions that could be useful to SDFormat, like the [ImplPtr](https://github.com/ignitionrobotics/ign-utils/blob/main/include/ignition/utils/ImplPtr.hh):

https://github.com/ignitionrobotics/ign-utils/

The dependency needs to be added on CI for all 3 platforms before it can be used here.

**Comment by scpeters** [comment]
done in https://github.com/osrf/sdformat/pull/474
