### ISSUE TITLE
Parsing failures can be hard to trace?

### ISSUE THREAD

**Issue by EricCousineau-TRI** [osrf/sdformat#479]
Relates @azeey's https://github.com/RobotLocomotion/drake/pull/14401

In internal code, I'm reviewing some failures that look like the following:
```
Error [Param.cc:354] Unknown error. Unable to set value [1.25 0.55 0.53 ] for key[pose]
...
Error: Error reading element <pose>
Error: Error reading element <visual>
Error: Error reading element <link>
Error: Error reading element <model>
Error: Error reading element <sdf>
Error: Unable to read file:<badly_formed_thing>.sdf
```

Ideally, it'd be nice to get something like `{file}:{line}`, or something that gives more concrete (unambiguous) context hints.

~Or maybe even some sort of XPath-type hint, like `/sdf/model[@name="blerg"]/link[@name="boo"]/visual[2]/pose` (I had hacked something like this into `urdf_parser_py`: https://github.com/ros/urdf_parser_py/pull/14 )~
Split XPath to separate issue: #510

**Comment by scpeters** [comment]
related to https://github.com/osrf/sdformat/issues/226#issuecomment-629556741
