### ISSUE TITLE
Pose tag in sensors ignored with fixed links

### ISSUE THREAD

**Issue by osrf-migration** [osrf/sdformat#67]
**Original report ([archived issue](https://osrf-migration.github.io/sdformat-gh-pages/#!/osrf/sdformat/issues/67)) by adhenning (Bitbucket: [adhenning](https://bitbucket.org/%7Baa99a57e-7bf1-4a88-ad27-a3cdd36e629c%7D/)).**

The original report had attachments: [GearsBot.URDF](https://osrf-migration.github.io/sdformat-gh-pages/data/repositories/osrf/sdformat/issues/67/attachments/GearsBot.URDF)

----------------------------------------
When a sensor (or at least camera's in this case) is attached to a fixed link, it's pose tag is ignored and overwritten with the computed pose for the fixed link when the pose tag should be transformed by the computed pose. I've attach the file to reproduce this issue. The following cases show the error. The pose should change, but doesn't.

No pose (0, 0, 0, 0, 0, 0):

    <sensor name="robotCamera" type="camera">
      <visualize>true</visualize>
      
      <camera></camera>
    </sensor>

Output:

    $ gz sdf -p /usr/share/frcsim/models/GearsBot/robots/GearsBot.URDF | awk "/<sensor name='robotCamera/,/<\/sensor>/"
      <sensor name='robotCamera' type='camera'>
        <visualize>1</visualize>
        <camera name='__default__'>
          <horizontal_fov>1.047</horizontal_fov>
          <image>
            <width>320</width>
            <height>240</height>
          </image>
          <clip>
            <near>0.1</near>
            <far>100</far>
          </clip>
        </camera>
        <pose>-0.20115 0.42488 0.30943 1.5708 -0.89012 1.5708</pose>
      </sensor>

Pose:

    <sensor name="robotCamera" type="camera">
      <visualize>true</visualize>
      <pose>1 1 1 1.570796 1.570796 1.570796</pose>
      <camera></camera>
    </sensor>

Output:

      $ gz sdf -p /usr/share/frcsim/models/GearsBot/robots/GearsBot.URDF | awk "/<sensor name='robotCamera/,/<\/sensor>/"
      <sensor name='robotCamera' type='camera'>
        <visualize>1</visualize>
        <camera name='__default__'>
          <horizontal_fov>1.047</horizontal_fov>
          <image>
            <width>320</width>
            <height>240</height>
          </image>
          <clip>
            <near>0.1</near>
            <far>100</far>
          </clip>
        </camera>
        <pose>-0.20115 0.42488 0.30943 1.5708 -0.89012 1.5708</pose>
      </sensor>

**Comment by peci1** [comment]
There's even a TODO for it in the code: https://github.com/osrf/sdformat/blob/master/src/parser_urdf.cc#L3374 . This issue is very impractical...

**Comment by peci1** [comment]
Fixed by https://github.com/osrf/sdformat/pull/525 .

**Comment by peci1** [comment]
The fix has been released. This bug can be closed now, @nkoenig .
