### ISSUE TITLE
URDF parsing seg-fault on OSX 10.8

### ISSUE THREAD

**Issue by osrf-migration** [osrf/sdformat#74]
**Original report ([archived issue](https://osrf-migration.github.io/sdformat-gh-pages/#!/osrf/sdformat/issues/74)) by Steve Peters (Bitbucket: [Steven Peters](https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/), GitHub: [scpeters](https://github.com/scpeters)).**

----------------------------------------
It's really weird; I'm only able reproduce this on my laptop running OSX 10.8.5. With the home-brew versions or urdfdom and console_bridge installed, and building the `sdf_2.0` branch with `-DUSE_EXTERNAL_URDF=True`.

I observe seg-faulting of the `INTEGRATION_fixed_joint_reduction` and `PERFORMANCE_parser_urdf` tests.

From some extensive debugging, I've seen that the parser is unable to properly cast some of the URDF data types. For example, the cast from `urdf::Geometry` to `urdf::Box` in [sdf::CreateGeometry](https://github.com/osrf/sdformat/blob/master/src/parser_urdf.cc#L1673) is unsuccessful, which causes the seg-faults. The following is a workaround that prevents the seg-faults:
~~~
diff -r 675bd271feb80485067835704b966f8b57a8bf1c src/parser_urdf.cc
--- a/src/parser_urdf.cc	Fri Sep 12 11:13:09 2014 -0700
+++ b/src/parser_urdf.cc	Wed Oct 01 14:31:48 2014 -0700
@@ -1673,9 +1673,19 @@
         box = boost::dynamic_pointer_cast< const urdf::Box >(_geom);
         int sizeCount = 3;
         double sizeVals[3];
-        sizeVals[0] = box->dim.x;
-        sizeVals[1] = box->dim.y;
-        sizeVals[2] = box->dim.z;
+        if (box)
+        {
+          sizeVals[0] = box->dim.x;
+          sizeVals[1] = box->dim.y;
+          sizeVals[2] = box->dim.z;
+        }
+        else
+        {
+          std::cerr << "Failed to cast to urdf::BoxPtr" << std::endl;
+          sizeVals[0] = 1.0;
+          sizeVals[1] = 1.0;
+          sizeVals[2] = 1.0;
+        }
         geometryType = new TiXmlElement(type);
         AddKeyValue(geometryType, "size",
             Values2str(sizeCount, sizeVals));
~~~
This is really weird.

**Comment by scpeters** [comment]
this is for an old version, and it doesn't affect new versions; closing
