### ISSUE TITLE
gz sdf command-line tool should be in sdformat

### ISSUE THREAD

**Issue by osrf-migration** [osrf/sdformat#85]
**Original report ([archived issue](https://osrf-migration.github.io/sdformat-gh-pages/#!/osrf/sdformat/issues/85)) by Steve Peters (Bitbucket: [Steven Peters](https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/), GitHub: [scpeters](https://github.com/scpeters)).**

----------------------------------------
The `gz sdf` command line tool really should be in this repository. It's a pain to compile all of gazebo just to use `gz sdf`, when it doesn't use anything special from gazebo.

**Comment by catskul** [comment]
ping

**Comment by chapulina** [comment]
The equivalent `ign sdf` tool was added to SDFormat on [this PR](https://osrf-migration.github.io/sdformat-gh-pages/#!/osrf/sdformat/pull-requests/346/page/1).

**Comment by catskul** [comment]
was kind of surprised this tool isn't directly a part of `sdformat` itself. Is that because of all the file system searching necessary that's tied to `gazebo`/`ign`?

**Comment by chapulina** [comment]
I believe it was just more convenient to implement the command using [ign-tools](https://github.com/ignitionrobotics/ign-tools/) than duplicating a lot of the code inside SDFormat.
