### ISSUE TITLE
(SDF Spec) clarify the semantic of having multiple links in a model.

### ISSUE THREAD

**Issue by osrf-migration** [osrf/sdformat#94]
**Original report ([archived issue](https://osrf-migration.github.io/sdformat-gh-pages/#!/osrf/sdformat/issues/94)) by sylvainjoyeux (Bitbucket: [sylvainjoyeux](https://bitbucket.org/%7B11579fb5-6368-4ec9-a820-10579e368fe7%7D/)).**

----------------------------------------
This is a follow-up to [this question](http://answers.gazebosim.org/question/8582/whats-the-semantic-of-having-multiple-toplevel/)

The current behaviour of Gazebo is that the first link inside a model defines the model's pose (i.e. the model's frame is rigidly attached to the link). However, subsequent links that are not attached to it through a joint are completely free. I am specifically referring to Gazebo, as [the SDF spec itself](http://sdformat.org/spec?ver=1.5&elem=model#model_link) is very unspecific about this issue. 

I find that quite a big magic, and very unintuitive. After reading quite a bit of Gazebo's API documentation, I, and other people within my team, went to the (wrong) conclusion that all "toplevel" links (links that are not children in a joint) would be fixed in the model frame.

I see two ways to solve this:
1. change the link behaviour
2. fix at least the SDF specification to clarify the relationship between links and model

I would personally very much prefer (1), but I guess that (2) would be the path of least resistance.

**Comment by scpeters** [comment]
This is an old discussion, so I'm going to close it. Please re-open if you think further action should be taken.
